# Generated by Django 5.0.6 on 2024-05-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='cfg_scale',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='model',
            name='sampler_name',
            field=models.CharField(default='Euler a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='sampler_steps',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/'),
        ),
        migrations.AddField(
            model_name='request',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.model'),
            preserve_default=False,
        ),
    ]
