# Generated by Django 5.0.6 on 2024-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_model_cfg_scale_model_sampler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='cfg_scale',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='sampler_name',
            field=models.CharField(default='Euler_a', max_length=100),
        ),
    ]
